import {spawn} from 'node:child_process';
import {mkdirSync, writeFileSync} from 'node:fs';
import {dirname, join} from 'node:path';
import {fileURLToPath} from 'node:url';
import {chromium} from 'playwright-core';

const root = dirname(fileURLToPath(import.meta.url));
const site = join(root, '..', 'site');
const out = join(root, 'out');
const port = Number(process.env.QA_PORT || 8765);
const base = `http://127.0.0.1:${port}/`;
const chrome = process.env.CHROME_PATH || '/usr/bin/google-chrome';
mkdirSync(out, {recursive: true});

const results = [];
function check(name, ok, detail = '') {
  results.push({name, ok: Boolean(ok), detail});
  console.log(`${ok ? 'OK  ' : 'FAIL'} ${name}${detail ? ' :: ' + detail : ''}`);
}

const server = spawn('python3', ['-m', 'http.server', String(port), '--bind', '127.0.0.1', '--directory', site], {stdio: 'ignore'});
await new Promise(r => setTimeout(r, 800));
const browser = await chromium.launch({executablePath: chrome, headless: true});

try {
  const page = await browser.newPage({viewport: {width: 1440, height: 1000}});
  const consoleErrors = [];
  page.on('console', m => { if (m.type() === 'error') consoleErrors.push(m.text()); });
  page.on('pageerror', e => consoleErrors.push(String(e)));
  const qa = fn => page.evaluate(fn);
  const settle = async () => {
    await page.waitForFunction(() => window.ATLAS_QA && window.ATLAS_QA.ready && document.getElementById('loading').hidden, null, {timeout: 60000});
    await page.waitForTimeout(150);
  };
  const choose = async (id, value) => { await page.selectOption('#' + id, value); await settle(); };
  const fill = async (id, value) => { await page.fill('#' + id, value); await page.waitForTimeout(100); };

  let t0 = Date.now();
  await page.goto(base);
  await settle();
  check('carrega nível nacional', (await qa(() => window.ATLAS_QA.state().level)) === 'br', `${Date.now() - t0} ms`);
  const meta = await page.evaluate(() => fetch('data/meta.json').then(r => r.json()));
  check('reconciliação do build sem divergências', meta.checks.failed === 0 && Object.keys(meta.checks.invariant_violations).length === 0, JSON.stringify(meta.checks.info));
  let terr = await qa(() => window.ATLAS_QA.territory());
  check('Brasil: comparecimento = feed TSE', terr.comp === 125275835, String(terr.comp));
  check('Brasil: Samara (80) = feed TSE', terr['1.80'] === 122911, String(terr['1.80']));
  check('Brasil: 28 UFs (com exterior) na lista', (await qa(() => window.ATLAS_QA.list())) === 28);
  check('Brasil: 27 áreas de UF no mapa', (await qa(() => window.ATLAS_QA.drawn.areas)) === 27);
  check('indicador padrão é a UP', (await page.inputValue('#metric')) === '1.80');
  const presidentMetrics = await qa(() => window.ATLAS_QA.metrics());
  check('Presidente: só Lula, Flávio e Samara', JSON.stringify(meta.president.map(c => c.n).sort()) === '["13","22","80"]' && presidentMetrics.filter(k => /^1\.\d+$/.test(k)).length === 3, presidentMetrics.join(','));
  check('ordem: Samara, Lula, Flávio, blocos, válidos, brancos e nulos, brancos, nulos', presidentMetrics.slice(0, 11).join() === '1.80,1.13,1.22,1.left,1.margin,1.valid,1.bn,1.blank,1.null,1.up22,1.chg', presidentMetrics.join());
  check('Brasil: campo da esquerda presidencial = feed TSE (Lula + Samara + PCB + PSTU)', terr['1.left'] === 54068245, String(terr['1.left']));
  check('Brasil: PL presidencial = Flávio no feed TSE', terr['1.pl'] === 56104503, String(terr['1.pl']));
  check('Brasil: esquerda x PL = diferença das contagens', terr['1.margin'] === 54068245 - 56104503, String(terr['1.margin']));
  check('tooltip do campo da esquerda presente no seletor', (await page.$('#metric-tip .tip')) !== null);
  await page.hover('#metric-tip .tip');
  const tipText = await qa(() => window.ATLAS_QA.tip());
  check('tooltip explica partidos e regra da coligação', tipText && tipText.includes('PCdoB') && tipText.includes('não a coligação'), tipText);
  await page.screenshot({path: join(out, 'tooltip-esquerda.png'), clip: {x: 0, y: 0, width: 1440, height: 1000}});
  await page.mouse.move(5, 5);
  check('Brasil: UP 2022 para Presidente = 53.519 (resultado oficial)', terr['1.up22'] === 53519, String(terr['1.up22']));
  check('Brasil: variação presidencial = 122.911 - 53.519 votos', terr['1.chg'] === 122911 - 53519, String(terr['1.chg']));
  check('página sem a seção do vídeo, sem "pipeline determinístico" e sem "Modelo visual"', !(await page.$('#video')) && !(await page.textContent('body')).includes('pipeline determinístico') && !(await page.textContent('body')).includes('Modelo visual'));
  await choose('metric', '1.chg');
  check('variação 2022 x 2026 no Brasil: mapa de áreas', (await page.$$eval('#view option', os => os.map(o => o.value).join())) === 'choro');
  await page.locator('.map-grid').screenshot({path: join(out, 'brasil-variacao-2022.png')});
  await choose('metric', '1.80');
  check('matriz de correlação no nível nacional', (await qa(() => window.ATLAS_QA.corrSize())) >= 8, String(await qa(() => window.ATLAS_QA.corrSize())));
  await page.screenshot({path: join(out, 'brasil-desktop.png'), fullPage: false});
  await page.locator('.map-grid').screenshot({path: join(out, 'brasil-mapa.png')});

  await choose('office', '5');
  check('Senador nacional: indicador UP no cargo', (await page.inputValue('#metric')) === '5.up');
  terr = await qa(() => window.ATLAS_QA.territory());
  check('Senador nacional: votos UP > 0', terr['5.up'] > 0, String(terr['5.up']));
  check('Senador nacional: blocos no seletor', ['5.left', '5.pl', '5.margin'].every(k => terr[k] !== undefined) && (await qa(() => window.ATLAS_QA.metrics())).includes('5.left'));
  await choose('metric', '5.margin');
  check('Esquerda x PL: só a visualização de áreas', (await page.$$eval('#view option', os => os.map(o => o.value).join())) === 'choro');
  await page.locator('.map-grid').screenshot({path: join(out, 'brasil-senado-esquerda-x-pl.png')});
  await choose('office', '1');

  t0 = Date.now();
  await choose('uf', 'MG');
  check('MG: nível estadual', (await qa(() => window.ATLAS_QA.state().level)) === 'uf', `${Date.now() - t0} ms`);
  check('MG: 853 municípios na lista', (await qa(() => window.ATLAS_QA.list())) === 853);
  check('MG: 853 áreas municipais', (await qa(() => window.ATLAS_QA.drawn.areas)) === 853);
  await page.screenshot({path: join(out, 'mg-desktop.png')});
  await choose('office', '5');
  terr = await qa(() => window.ATLAS_QA.territory());
  check('MG Senador: campo da esquerda = feed TSE', terr['5.left'] === 6715519, String(terr['5.left']));
  check('MG Senador: PL = feed TSE', terr['5.pl'] === 4968829, String(terr['5.pl']));
  check('MG Senador: candidaturas de PT, PSOL, PSTU, UP e PL no seletor', ['5.131', '5.500', '5.161', '5.808', '5.222'].every(k => terr[k] > 0));
  check('MG Senador: tabela de candidaturas com blocos fixados no topo', (await page.$$eval('#candidates-body tr.pinned', rs => rs.length)) === 2);
  await choose('office', '3');
  terr = await qa(() => window.ATLAS_QA.territory());
  check('MG Governador: blocos = feed TSE', terr['3.left'] === 3042471 && terr['3.pl'] === 795193, `${terr['3.left']} / ${terr['3.pl']}`);
  check('MG Governador: UP 2022 = 15.604', terr['3.up22'] === 15604, String(terr['3.up22']));
  await choose('metric', '3.chg');
  await page.locator('.map-grid').screenshot({path: join(out, 'mg-governador-variacao-2022.png')});
  await choose('metric', '3.margin');
  await page.locator('.map-grid').screenshot({path: join(out, 'mg-governador-esquerda-x-pl.png')});
  await choose('office', '1');
  await page.locator('.map-grid').screenshot({path: join(out, 'mg-mapa.png')});
  await choose('view', 'count');
  check('MG: círculos de contagem desenhados', (await qa(() => window.ATLAS_QA.drawn.markers)) > 0);
  await choose('view', 'choro');

  await choose('mun', '54038');
  terr = await qa(() => window.ATLAS_QA.territory());
  const ref = {aptos: 540033, comp: 429516, abst: 110517, '1.valid': 409921, '1.blank': 7763, '1.null': 11832, '1.13': 163879, '1.22': 206793, '1.80': 399};
  check('Uberlândia: totais iguais ao atlas de referência', Object.entries(ref).every(([k, v]) => terr[k] === v), JSON.stringify(Object.fromEntries(Object.keys(ref).map(k => [k, terr[k]]))));
  check('Uberlândia: brancos e nulos = 19.595', terr['1.bn'] === 19595, String(terr['1.bn']));
  check('Uberlândia: 137 locais', (await qa(() => window.ATLAS_QA.list())) === 137);
  check('Uberlândia: 137 marcadores no mapa', (await qa(() => window.ATLAS_QA.drawn.markers)) === 137);
  check('Uberlândia: calor sem pontos zerados', (await qa(() => window.ATLAS_QA.drawn.heat)) === 119, String(await qa(() => window.ATLAS_QA.drawn.heat)));
  check('Uberlândia: ocupação de urnas da Samara = 354 seções', terr['1.80#s'] === 354, String(terr['1.80#s']));
  let corr = await qa(() => window.ATLAS_QA.corr('1.80', '1.13'));
  check('correlação Samara x Lula = referência Python', corr && corr.n === 137 && Math.abs(corr.rho - (-0.2607585103639025)) < 1e-9, JSON.stringify(corr && {rho: corr.rho, n: corr.n}));
  corr = await qa(() => window.ATLAS_QA.corr('1.80', '5.up'));
  check('correlação entre cargos (Samara x UP Senado) = referência Python', corr && Math.abs(corr.rho - 0.115143298408016) < 1e-9, String(corr && corr.rho));
  await page.click('#corr-box .corr-cell');
  check('Uberlândia: UP 2022 por cargo', terr['1.up22'] === 152 && terr['3.up22'] === 839 && terr['5.up22'] === null && terr['6.up22'] === 122 && terr['7.up22'] === 319, JSON.stringify(['1', '3', '5', '6', '7'].map(o => terr[o + '.up22'])));
  await choose('metric', '1.chg');
  check('variação no município: só zonas no mapa e lista por zona', (await page.$$eval('#view option', os => os.map(o => o.value).join())) === 'zones' && (await qa(() => window.ATLAS_QA.list())) === 5);
  const zone278 = (await qa(() => window.ATLAS_QA.rows())).find(r => r.zone === 278);
  check('zona 278: UP 2022 = 29 e variação calculada', zone278 && zone278.values['1.up22'] === 29 && zone278.values['1.chg'] === zone278.values['1.80'] - 29, JSON.stringify(zone278 && zone278.values['1.up22']));
  check('tabela de zonas com colunas de 2022', (await page.textContent('#zones-body')).length > 0 && (await page.$$eval('#territory-tables th', ths => ths.some(t => t.textContent.includes('Variação desde 2022')))));
  let listHead = await page.$$eval('#places-head th', ths => ths.map(t => t.textContent));
  const once = (head, label) => head.filter(h => h === label).length === 1;
  check('lista com variação selecionada: indicador + coluna UP 2022, sem repetir a variação', once(listHead, 'UP 2022') && once(listHead, 'Variação desde 2022'), listHead.join('|'));
  await page.locator('.map-grid').screenshot({path: join(out, 'uberlandia-variacao-zonas.png')});
  await choose('metric', '1.up22');
  listHead = await page.$$eval('#places-head th', ths => ths.map(t => t.textContent));
  check('lista com UP 2022 selecionado: indicador + coluna Variação, sem repetir UP 2022', once(listHead, 'UP 2022') && once(listHead, 'Variação desde 2022'), listHead.join('|'));
  check('cabeçalho e células coincidem com colunas de 2022', listHead.length === await page.$$eval('#places-body tr:first-child td', tds => tds.length));
  await choose('metric', '1.80');
  listHead = await page.$$eval('#places-head th', ths => ths.map(t => t.textContent));
  check('lista com outro indicador: sem colunas de 2022', !listHead.some(h => h.includes('2022')), listHead.join('|'));
  await choose('view', 'heat');
  await choose('unit', 'place');
  check('clique na matriz abre a dispersão', (await page.$$eval('#corr-detail svg circle', cs => cs.length)) > 100);
  await page.locator('#correlacao').screenshot({path: join(out, 'uberlandia-correlacao.png')});
  await choose('view', 'zones');
  let drawn = await qa(() => window.ATLAS_QA.drawn);
  check('Uberlândia: zonas aproximadas desenhadas (5 zonas)', drawn.zones === 5 && drawn.areas >= 100 && drawn.boundaries > 0, JSON.stringify(drawn));
  await page.locator('.map-grid').screenshot({path: join(out, 'uberlandia-zonas.png')});
  await choose('unit', 'zone');
  check('lista por zona: 5 zonas', (await qa(() => window.ATLAS_QA.list())) === 5);
  check('lista por zona: soma igual ao município', (await qa(() => window.ATLAS_QA.sum('1.80'))) === 399);
  await page.click('#places-body .row-button');
  await page.waitForTimeout(200);
  check('ficha da zona abre', (await page.textContent('#detail')).includes('Zona eleitoral'));
  check('tabela candidaturas x zona', (await page.$$eval('#zone-matrix-body tr', rs => rs.length)) >= 3);
  await page.click('#reset');
  await choose('view', 'heat');

  await fill('min-value', '1');
  check('mínimo 1 por local: 119 locais com voto UP', (await qa(() => window.ATLAS_QA.list())) === 119);
  check('soma da seleção = 399', (await qa(() => window.ATLAS_QA.sum('1.80'))) === 399);
  await choose('unit', 'section');
  check('mínimo 1 por seção: 354 BUs', (await qa(() => window.ATLAS_QA.list())) === 354);
  check('modo seção: soma ainda 399', (await qa(() => window.ATLAS_QA.sum('1.80'))) === 399);
  await choose('sort', 'count-desc');
  check('ordenação não muda a soma', (await qa(() => window.ATLAS_QA.sum('1.80'))) === 399);
  await fill('min-value', '');
  await choose('zone', '278');
  await fill('section-filter', '7');
  check('zona 278 + seção 7: uma linha', (await qa(() => window.ATLAS_QA.list())) === 1);
  await page.click('#places-body .row-button');
  await page.waitForTimeout(200);
  const detail = await page.textContent('#detail');
  check('ficha da seção abre com o local', detail.includes('seção 7'), detail.slice(0, 80));
  await fill('min-value', '10');
  await fill('max-value', '2');
  check('faixa inválida: lista vazia e enquadrar desabilitado', (await qa(() => window.ATLAS_QA.list())) === 0 && await page.isDisabled('#fit'));
  await page.click('#reset');
  await page.waitForTimeout(200);
  check('limpar filtros volta a 137 locais', (await qa(() => window.ATLAS_QA.list())) === 137 && (await page.inputValue('#unit')) === 'place');
  await fill('query', 'jacy de assis');
  check('busca sem acento encontra o local', (await qa(() => window.ATLAS_QA.list())) >= 1);
  await page.click('#reset');
  await choose('view', 'rate');
  check('modo percentual sem camada de calor', (await qa(() => window.ATLAS_QA.drawn.heat)) === 0);
  await choose('view', 'heat');
  const headCells = await page.$$eval('#places-head th', ths => ths.length);
  const rowCells = await page.$$eval('#places-body tr:first-child td', tds => tds.length);
  check('cabeçalho e células da lista coincidem', headCells === rowCells, `${headCells}/${rowCells}`);
  await page.screenshot({path: join(out, 'uberlandia-desktop.png')});
  await page.locator('.map-grid').screenshot({path: join(out, 'uberlandia-mapa.png')});

  await choose('office', '5');
  terr = await qa(() => window.ATLAS_QA.territory());
  check('Uberlândia Senador: UP no cargo = 2196', terr['5.up'] === 2196, String(terr['5.up']));
  check('Senado MG sem candidatura UP em 2022: nota explica', (await page.textContent('#up-note')).includes('Em 2022 a UP não teve candidatura'));
  corr = await qa(() => window.ATLAS_QA.corr('5.left', '1.13'));
  check('correlação Senado esquerda x Lula = referência Python', corr && Math.abs(corr.rho - 0.897352847835421) < 1e-9, String(corr && corr.rho));
  await choose('metric', '5.margin');
  check('Esquerda x PL no município: círculos de percentual e zonas', (await page.$$eval('#view option', os => os.map(o => o.value).join())) === 'rate,zones');
  await choose('view', 'zones');
  await page.locator('.map-grid').screenshot({path: join(out, 'uberlandia-senado-zonas-esquerda-x-pl.png')});
  const senateMetrics = await qa(() => window.ATLAS_QA.metrics());
  check('Senador: candidaturas UP 800 e 808 disponíveis', senateMetrics.includes('5.800') && senateMetrics.includes('5.808'));
  const senateCards = await page.textContent('#city-cards');
  check('Senador: denominador de 2 votos por eleitor explicado', senateCards.includes('2 por eleitor'));
  await choose('office', '6');
  check('Deputado Federal: legenda e candidaturas UP', (await qa(() => window.ATLAS_QA.metrics())).includes('6.80'));
  await page.screenshot({path: join(out, 'uberlandia-depfed.png')});

  await page.click('#expand');
  await page.waitForTimeout(200);
  check('ampliar mapa', await page.$eval('#atlas', el => el.classList.contains('map-expanded')));
  await page.keyboard.press('Escape');
  await page.waitForTimeout(200);
  check('Escape fecha a ampliação', !(await page.$eval('#atlas', el => el.classList.contains('map-expanded'))));

  const tiles = await qa(() => window.ATLAS_QA.tiles());
  check('mapa-base carregou tiles', tiles.loaded > 0, JSON.stringify(tiles));

  t0 = Date.now();
  await page.goto(base + '#cargo=1&uf=SP&mun=71072&indicador=1.80&vis=heat');
  await settle();
  const spLoad = Date.now() - t0;
  const spPlaces = await qa(() => window.ATLAS_QA.list());
  check('link direto para São Paulo/SP', (await qa(() => window.ATLAS_QA.state().mun)) === '71072', `${spPlaces} locais, ${spLoad} ms`);
  check('São Paulo: paginação ativa', (await page.textContent('#pager-top')).includes('Página 1 de'));
  t0 = Date.now();
  await choose('unit', 'section');
  check('São Paulo: modo seção (~26 mil BUs) responde', (await qa(() => window.ATLAS_QA.list())) > 20000, `${Date.now() - t0} ms`);
  await page.screenshot({path: join(out, 'sao-paulo-desktop.png')});
  await choose('unit', 'place');
  t0 = Date.now();
  await choose('view', 'zones');
  const spZones = Date.now() - t0;
  drawn = await qa(() => window.ATLAS_QA.drawn);
  check('São Paulo: zonas aproximadas em menos de 5 s', drawn.zones > 50 && drawn.areas > 1500 && spZones < 5000, `${JSON.stringify(drawn)} ${spZones} ms`);
  await page.locator('.map-grid').screenshot({path: join(out, 'sao-paulo-zonas.png')});

  await page.goto(base + '#cargo=5&uf=MG&mun=41238&indicador=5.left&vis=zones');
  await settle();
  drawn = await qa(() => window.ATLAS_QA.drawn);
  check('Belo Horizonte: zonas aproximadas (comparação com o onrender)', drawn.zones >= 18 && drawn.boundaries > 0, JSON.stringify(drawn));
  await page.locator('.map-grid').screenshot({path: join(out, 'bh-senado-esquerda-zonas.png')});

  await page.goto(base + '#cargo=1&uf=SP&mun=66052&indicador=1.chg&vis=zones');
  await settle();
  terr = await qa(() => window.ATLAS_QA.territory());
  const jarinu = (await qa(() => window.ATLAS_QA.rows()))[0];
  check('Jarinu (zona 16 virou 344): total comparável, zona sem correspondência', terr['1.up22'] === 13 && terr['1.chg'] !== null && jarinu.values['1.chg'] === null, JSON.stringify({total: terr['1.up22'], zone: jarinu.values['1.chg']}));

  const shared = base + '#cargo=1&uf=MG&mun=54038&indicador=1.80&vis=rate&zona=278&max=50&unidade=section&ordem=count-desc&sel=s278-7';
  await page.goto(shared);
  await settle();
  check('URL restaura filtros (zona, máximo, unidade, ordem)', (await page.inputValue('#zone')) === '278' && (await page.inputValue('#max-value')) === '50' && (await page.inputValue('#unit')) === 'section' && (await page.inputValue('#sort')) === 'count-desc' && (await page.inputValue('#view')) === 'rate');
  check('URL restaura a ficha selecionada', (await page.textContent('#detail')).includes('seção 7'));
  await fill('query', 'escola');
  const hash = await page.evaluate(() => location.hash);
  check('URL acompanha cada alteração', hash.includes('busca=escola') && hash.includes('zona=278') && hash.includes('sel=s278-7'), hash);
  await page.click('#corr-box .corr-cell');
  const withCorr = await page.evaluate(() => location.hash);
  const fresh = await browser.newPage({viewport: {width: 1440, height: 1000}});
  await fresh.goto(base + withCorr);
  await fresh.waitForFunction(() => window.ATLAS_QA && window.ATLAS_QA.ready, null, {timeout: 60000});
  await fresh.waitForTimeout(300);
  check('link copiado reabre o mesmo recorte, filtros, ficha e dispersão', (await fresh.evaluate(() => location.hash)) === withCorr && (await fresh.$$eval('#corr-detail svg circle', cs => cs.length)) > 0 && (await fresh.inputValue('#query')) === 'escola', await fresh.evaluate(() => location.hash));
  await fresh.close();

  await page.goto(base + '#cargo=5&uf=ZZ');
  await settle();
  const zz = await qa(() => window.ATLAS_QA.state());
  check('Exterior força Presidente', zz.uf === 'ZZ' && zz.office === 1);
  check('Exterior lista cidades', (await qa(() => window.ATLAS_QA.list())) > 50);

  await page.goto(base + '#cargo=3&uf=AC');
  await settle();
  check('UF sem candidatura UP explica a ausência', (await page.textContent('#up-note')).includes('não teve candidatura'));

  check('console sem erros', consoleErrors.length === 0, consoleErrors.slice(0, 3).join(' | '));

  const mobile = await browser.newPage({viewport: {width: 390, height: 844}, isMobile: true});
  await mobile.goto(base + '#cargo=1&uf=MG&mun=54038');
  await mobile.waitForFunction(() => window.ATLAS_QA && window.ATLAS_QA.ready, null, {timeout: 60000});
  await mobile.waitForTimeout(500);
  const overflow = await mobile.evaluate(() => document.documentElement.scrollWidth - window.innerWidth);
  check('mobile 390px sem rolagem horizontal da página', overflow <= 0, `${overflow}px`);
  await mobile.screenshot({path: join(out, 'uberlandia-mobile.png')});
  await mobile.close();
} finally {
  await browser.close();
  server.kill();
  writeFileSync(join(out, 'resultado-testes.json'), JSON.stringify({at: new Date().toISOString(), results}, null, 2));
}

const failed = results.filter(r => !r.ok);
console.log(`\n${results.length - failed.length}/${results.length} verificações aprovadas`);
process.exit(failed.length ? 1 : 0);
